# PR labels and the branch patterns they should be auto-assigned to
✨ New Feature: ["FEATURE/*", "FEAT/*"]
🚚 Refactor: ["IMPROVMENTS/*", "REFACTOR/*"]
🦋 Bug Fix: ["FIX/*", "HOT-FIX/*", "BUG-FIX/*"]
💯 Showcase: ["SHOWCASE/*", "SHOWCASE_SUBMISSION/*"]
💄 Stylistic Changes: ["STYLES/*", "THEME/*", "UI/*"]
🏗️ Architectural Changes: ["ARCH/*", "ARCHITECTURE/*"]
🌐 Language: ["LANG/*", "INTERNATIONALIZATION/*", "I18N/*", "TEXT-UPDATE/*"]
🤖 Auto: ["AUTO/*", "BOT/*", "snyk-upgrade-*", "snyk-fix-*"]
