version: '0.2'
language: en
files:
  - .github/**/*.{md,txt,yaml,yml}
  - .git/COMMIT_EDITMSG
  - '*.{md,txt,yaml,yml}'
  - dictionaries/**/*.{md,txt,yaml,yml,js,tex}
  - docs/**/*.md
  - scripts/**
  - codetypo-dict-file-checker/**
  - shared-sources/**
  - LICENSE
words:
  - Affero
  - ALLCAPS
  - appname
  - autobuild
  - Bokmål
  - cli
  - cmds
  - codeql
  - configstore
  - crowdsourcing
  - codetypocache
  - dependabot
  - django
  - django's
  - EDITMSG
  - elisp
  - Français
  - globby
  - Glutanimate
  - googleapis
  - hunspell
  - issuehunt
  - Kieran
  - lgpl
  - LGPL
  - liberapay
  - mdash
  - medicalterms
  - monkeyc
  - nohoist
  - otechie
  - patreon
  - pipefail
  - prebuilds
  - Réforme
  - khulnasoft
  - Sublicensing
  - tidelift
  - WIPO
  - Wooorm's
  - wordlist
  - z
flagWords: []
maxNumberOfProblems: 1000
ignorePaths:
  - .gitignore
  - .vscode/**
  - '*-lock.yaml'
  - '*.aff'
  - '*.dic'
  - '*.gz'
  - '*.lock'
  - '*.log'
  - '*.snap'
  - '*.trie'
  - '**/.git/!(COMMIT_EDITMSG)'
  - '**/.git/!(COMMIT_EDITMSG)/**'
  - CHANGELOG.md
  - checksum.txt
  - codetypo.json
  - codetypo.json
  - dictionaries/*/dict/**/*.txt
  - dictionaries/*/src/**
  - generator-codetypo-dicts/generators/app/templates/**
  - lerna.json
  - node_modules
  - /package.json
  - shared-additional-words.txt
  - source-dependencies.txt
  - source-files.txt
  - snapshots/**
import: []
useGitignore: true
overrides:
  - filename: '**/nl_NL/**'
    language: en,nl
  - filename: '**/ru_RU/samples/**'
    language: ru,en
  - filename: '**/sv/**'
    language: en,sv
  - filename: '**/package.json'
    patterns:
      - name: devDependencies
        pattern: |
          /"devDependencies": \{[^}]*?\}/g
        description: Ignore "devDependencies"
    ignoreRegExpList:
      - devDependencies
cache:
  useCache: true
  cacheStrategy: content
enableFiletypes:
  - shellscript