blank_issues_enabled: false
contact_links:
  - name: For new corrections, see our monthly pinned issue
    url: https://github.com/khulnasoft/codetypo/issues
  - name: Ask a question
    about: For support or brainstorming
    url: https://github.com/khulnasoft/codetypo/discussions
